grails-app/controllers/com/property/controllers/pm/ReminderListController.groovy
package com.property.controllers.pm

import com.model.AppConstants
import com.model.general.PropertyAdminProperty
import com.model.information.PropertyReminder
import com.model.information.PropertyReminderNotif
import com.model.property.PropertyUnit
import com.property.utils.ControllerUtil
import grails.converters.JSON
import grails.core.GrailsApplication
import org.apache.commons.lang.exception.ExceptionUtils

import java.text.SimpleDateFormat

class ReminderListController {

    def springSecurityService
    def userService
    GrailsApplication grailsApplication
    
    def index() {
        log.debug "IN index... $params"
    }

    def listDatatable(){
        def pmId = springSecurityService.principal?.pmId
        def columns = ['pr.name', 'pr.description', 'pr.createdDate', 'ui.name', 'pr.isActive']
        def baseQuery = "FROM PropertyReminder pr, UserInfo ui WHERE pr.property.propertyManager.user.id = :pmId AND ui.user.id = pr.createdBy"
        def query = "SELECT pr, ui " + baseQuery
        def queryCount = "SELECT count(pr.id) " + baseQuery
        def queryParams = [pmId: pmId]
        def result = ControllerUtil.parseDatatablesQuery(PropertyReminder.class, params, query, queryCount, queryParams, columns)

        def objs = result.objs
        def aaData = []
        def sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
        objs.each{ arrObj ->
            def obj = arrObj[0]
            def userObj = arrObj[1]
            aaData.add([id:obj.id, name: obj.name, description: obj.description, createdBy: userObj.name,
                        createdDate:sdf.format(obj.createdDate), status: ControllerUtil.getActive(obj.isActive)])
        }
        result.aaData = aaData
        result.objs = null
        render result as JSON
    }

    def detail(){
        log.debug "IN detail... $params"
        def pmId = springSecurityService.principal?.pmId
        def obj = PropertyReminder.executeQuery("FROM PropertyReminder where id = :id AND property.propertyManager.user.id = :pmId",
                [id:params.id, pmId:pmId]).first()
        if(obj!=null) {
            def sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")

            def result = [id: params.id, name:obj.name, description:obj.description, createdBy: userService.getUserName(obj.createdBy), createdDate: sdf.format(obj.createdDate),
                          updatedBy: userService.getUserName(obj.updatedBy), reminderDay: obj.reminderDay, message: obj.message,
                          updatedDate: obj.updatedDate?sdf.format(obj.updatedDate):"", status: ControllerUtil.getActive(obj.isActive), isActive:obj.isActive]
            [detail: result]
        } else {
            flash.error = "Pengingat tidak ditemukan"
            redirect(action: 'index')
        }
    }

    def activate(){
        log.debug "IN activate... $params"
        def pmId = springSecurityService.principal?.pmId
        def isError = false, message = ''
        def obj = PropertyReminder.executeQuery("FROM PropertyReminder where id = :id AND property.propertyManager.user.id = :pmId",
                [id:params.id, pmId:pmId]).first()

        if(obj!=null){
            PropertyReminder.withTransaction { status ->
                try {
                    obj.isActive = AppConstants.FLAG_YES
                    obj.save()
                } catch (Exception e) {
                    log.error ExceptionUtils.getStackTrace(e)
                    status.setRollbackOnly()
                    isError = true
                    message = "Server bermasalah, coba lagi beberapa saat."
                }
            }
        } else {
            message = "Pengingat tidak ditemukan"
            redirect(action: 'index')
        }
        if(isError) {
            flash.error = message
            redirect(action: 'detail', params:params)
        } else {
            flash.message = "Pengingat sudah diaktifkan"
            redirect(action: 'index')
        }
    }

    def deactivate(){
        log.debug "IN deactivate... $params"
        def pmId = springSecurityService.principal?.pmId
        def isError = false, message = ''
        def obj = PropertyReminder.executeQuery("FROM PropertyReminder where id = :id AND property.propertyManager.user.id = :pmId",
                [id:params.id, pmId:pmId]).first()

        if(obj!=null){
            PropertyReminder.withTransaction { status ->
                try {
                    obj.isActive = AppConstants.FLAG_NO
                    obj.save()
                } catch (Exception e) {
                    log.error ExceptionUtils.getStackTrace(e)
                    status.setRollbackOnly()
                    isError = true
                    message = "Server bermasalah, coba lagi beberapa saat."
                }
            }
        } else {
            message = "Pengingat tidak ditemukan"
            redirect(action: 'index')
        }
        if(isError) {
            flash.error = message
            redirect(action: 'detail', params:params)
        } else {
            flash.message = "Pengingat sudah dinonaktifkan"
            redirect(action: 'index')
        }
    }

    def create(){
        log.debug "IN create... $params"
        def reminderPeriodeList = AppConstants.getReminderPeriodeList()
        def propertyList = PropertyAdminProperty.executeQuery("FROM PropertyAdminProperty WHERE propertyAdmin.id = :currentUser",
                [currentUser:springSecurityService.principal.id]).collect{ it.property }
        def prop = propertyList.get(0)
        if(params._action_create == 'Back'){
            [detail:[name:params.name, description:params.description, message:params.message, reminderDay:params.reminderDay], reminderPeriodeList:reminderPeriodeList]
        } else {
            [detail:[:], reminderPeriodeList:reminderPeriodeList]
        }
    }

    def confirmAdd(){
        log.debug "IN confirmAdd... $params"
        def name = params.name
        def description = params.description
        def message = params.message
        def reminderDay = params.reminderDay

        if(!ControllerUtil.hasValue(name) || !ControllerUtil.hasValue(message) || !ControllerUtil.hasValue(reminderDay)){
            flash.error = "Please fill all required fields"
            params._action_create = 'Back'
            redirect(action: 'create', params:params)
            return
        }

        def result = [name:name, description: description, message: message, reminderDay:reminderDay]
        result.action = 'Create Reminder'
        result.stage = 'Confirm'
        result.actionType = 'add'
        render(view:'confirm', model: [detail: result])
    }

    def submitAdd(){
        log.debug "IN submitAdd... $params"
        def currentUser = springSecurityService.principal?.id
        def name = params.name
        def description = params.description
        def message = params.message
        def reminderDay = params.reminderDay

        def result = [name:name, description: description, message: message, reminderDay:reminderDay,
                      actionType: 'add', action:'Create Reminder']
        def isError = false
        def msg = ""

        def propertyList = PropertyAdminProperty.executeQuery("FROM PropertyAdminProperty WHERE propertyAdmin.id = :currentUser",
                [currentUser:currentUser]).collect{ it.property }
        if(propertyList.size()>0){
            def prop = propertyList.get(0)
            PropertyReminder.withTransaction { status ->
                try {
                    def obj = new PropertyReminder()
                    obj.name = name
                    obj.description = description
                    obj.message = message
                    obj.reminderDay = Integer.parseInt(reminderDay)
                    obj.isActive = AppConstants.FLAG_YES
                    obj.createdBy = currentUser
                    obj.property = prop
                    obj.save(flush: true)
                } catch (Exception e){
                    log.error ExceptionUtils.getStackTrace(e)
                    status.setRollbackOnly()
                    isError = true
                    msg = "Server bermasalah, coba lagi beberapa saat."
                }
            }
        } else {
            flash.error = "Properti tidak ditemukan"
            redirect(action:"index")
            return
        }
        if(isError) {
            result.stage = 'Confirm'
            flash.error = msg
        } else {
            result.stage = 'Result'
            flash.message = "Pengingat berhasil ditambahkan"
        }
        render view: 'confirm', model: [detail: result]
    }

    def edit(){
        log.debug "IN edit... $params"
        def propertyList = PropertyAdminProperty.executeQuery("FROM PropertyAdminProperty WHERE propertyAdmin.id = :currentUser",
                [currentUser:springSecurityService.principal.id]).collect{ it.property }
        def prop = propertyList.get(0)
        def reminderPeriodeList = AppConstants.getReminderPeriodeList()
        if(params._action_edit == 'Back'){
            [detail: [id:params.id, name: params.name, description:params.description, message:params.message, reminderDay:params.reminderDay],
             reminderPeriodeList:reminderPeriodeList]
        } else {
            def pmId = springSecurityService.principal?.pmId
            def obj = PropertyReminder.executeQuery("FROM PropertyReminder where id = :id AND property.propertyManager.user.id = :pmId",
                    [id:params.id, pmId:pmId]).first()
            if (obj != null) {
                def result = [id:params.id, name:obj.name, description: obj.description, message:obj.message, reminderDay:obj.reminderDay,
                              actionType: 'edit', action: 'Edit Reminder', stage: 'Confirm']
                [detail: result]
            } else {
                flash.error = "Pengingat tidak ditemukan"
                redirect(action: 'index')
            }

grails-app/views/reminderList/confirm.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>${detail.stage} ${detail.action}</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Daftar Pengingat" description="Tambah dan Ubah Pengingat" />
        <ol class="breadcrumb">
            <li>Maintenance</li>
            <li><g:link controller="reminderList" action="index"><i class="fa fa-info"></i> Reminder List</g:link></li>
            <li>${detail.action}</li>
            <li class="active">${detail.stage}</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">${detail.stage}</h3>
            </div>
            <g:form action="${detail.actionType=='add'?'submitAdd':'submitEdit'}" class="form-horizontal" method="POST">
                <div class="box-body">
                    <property:alert message="${flash.message}" type="success" title="${detail.action}"/>
                    <property:alert message="${flash.error}" type="danger" title="${detail.action}"/>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="id" value="${detail.id}" />
                            <input type="hidden" name="name" value="${detail.name}" />
                            <p class="form-control-static">${detail.name}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Deskripsi:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="description" value="${detail.description}" />
                            <p class="form-control-static">${detail.description}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Ingatkan setiap tanggal:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="reminderDay" value="${detail.reminderDay}" />
                            <p class="form-control-static">${detail.reminderDay}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Pesan:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="message" value="${detail.message}" />
                            <p class="form-control-static preline">${detail.message}</p>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <g:if test="${detail.stage == 'Confirm'}">
                        <button type="button" onclick="window.history.back();" class="btn btn-default">Kembali</button>
                        <button type="submit" onclick="$.blockUI({ message: 'Sedang diproses, harap menunggu.' });" class="btn btn-info pull-right">Simpan</button>
                    </g:if>
                    <g:else>
                        <g:link controller="reminderList" action="index" class="btn btn-success pull-right">Selesai</g:link>
                    </g:else>
                </div>
            </g:form>
        </div>
    </section>
</body>
</html>

grails-app/views/reminderList/create.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Add Reminder</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Daftar Pengingat" description="Tambah dan Ubah Pengingat" />
        <ol class="breadcrumb">
            <li>Maintenance</li>
            <li><g:link controller="reminderList" action="index"><i class="fa fa-info"></i> Reminder List</g:link></li>
            <li class="active">Add Reminder</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Tambah Pengingat</h3>
            </div>
            <g:form action="confirmAdd" class="form-horizontal" method="POST" name="form1">
                <div class="box-body">
                    <property:alert message="${flash.message}" type="success"/>
                    <property:alert message="${flash.error}" type="danger"/>
                    <div class="form-group">
                        <label for="tfName" class="col-sm-3 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <input type="text" name="name" class="form-control" id="tfName" maxlength="200" placeholder="Name" value="${detail.name}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tfDescription" class="col-sm-3 control-label">Deskripsi:</label>
                        <div class="col-sm-8">
                            <input type="text" name="description" class="form-control" id="tfDescription" maxlength="200" placeholder="Description" value="${detail.description}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Ingatkan setiap tanggal:</label>
                        <div class="col-sm-8">
                            <input type="number" name="reminderDay" placeholder="1-28" class="form-control" maxlength="2" value="${detail.reminderDay}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Pesan:</label>
                        <div class="col-sm-8">
                            <textarea rows="4" cols="50" name="message" class="form-control" placeholder="Message" maxlength="500" required>${detail.message}</textarea>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <g:link controller="reminderList" action="index" class="btn btn-default">Batal</g:link>
                    <button type="submit" class="btn btn-info pull-right">Konfirmasi</button>
                </div>
            </g:form>
        </div>
    </section>

    <script>
        $(document).ready(function(){
            $('#form1').validate({
                rules: {
                    reminderDay: {
                        required: true,
                        greaterThanZero: true
                    },
                    deadline: {
                        required: true,
                        greaterThanZero: true
                    }
                },
                submitHandler: function(form) {
                    $.blockUI({ message: 'Sedang diproses, harap menunggu.' });
                    form.submit();
                }
            });
        });
    </script>
</body>
</html>

grails-app/views/reminderList/detail.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Detail Reminder</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Daftar Pengingat" description="Tambah dan Ubah Pengingat" />
        <ol class="breadcrumb">
            <li>Maintenance</li>
            <li><g:link controller="reminderList" action="index"><i class="fa fa-info"></i> Reminder List</g:link></li>
            <li class="active">Detail Reminder</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Detail</h3>
            </div>
            <div class="box-body" id="testBody">
                <property:alert message="${flash.message}" type="success"/>
                <property:alert message="${flash.error}" type="danger"/>
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.name}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Deskripsi:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.description}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Ingatkan setiap tanggal:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.reminderDay}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Pesan:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static preline">${detail.message}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Status:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.status}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Dibuat oleh:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.createdBy} on ${detail.createdDate}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Diubah oleh:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.updatedBy} on ${detail.updatedDate}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <g:link controller="reminderList" action="index" class="btn btn-default">Kembali</g:link>
                <div class="pull-right">
                    <g:link controller="reminderList" action="edit" params="[id:detail.id]" class="btn btn-info"><i class="fa fa-pencil"></i> Ubah</g:link>
                    <g:if test="${detail.isActive=="Y"}">
                        <button type="button" onclick="confirmAction('mendeaktivasi')" class="btn btn-danger"><i class="fa fa-times"></i> Nonaktifkan</button>
                    </g:if>
                    <g:else>
                        <button type="button" onclick="confirmAction('mengaktivasi')" class="btn btn-danger"><i class="fa fa-check"></i> Aktivasi</button>
                    </g:else>
                </div>
            </div>
        </div>
    </section>

    <g:form name="formDeactivate" controller="reminderList" action="deactivate" method="POST">
        <input type="hidden" name="id" value="${detail.id}" />
    </g:form>

    <g:form name="formActivate" controller="reminderList" action="activate" method="POST">
        <input type="hidden" name="id" value="${detail.id}" />
    </g:form>

    <script>
        function confirmAction(msg){
            vex.dialog.confirm({
                message: 'Apakah anda yaking ingin '+msg+' reminder ini?',
                callback: function (value) {
                    if (value) {
                        if(msg=='mendeaktivasi'){
                            $('#formDeactivate').submit();
                        } else {
                            $('#formActivate').submit();
                        }
                    }
                }
            });
        }
    </script>
</body>
</html>

grails-app/views/reminderList/edit.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Edit Reminder</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Daftar Pengingat" description="Tambah dan Ubah Pengingat" />
        <ol class="breadcrumb">
            <li>Maintenance</li>
            <li><g:link controller="reminderList" action="index"><i class="fa fa-info"></i> Reminder List</g:link></li>
            <li class="active">Edit Reminder</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Ubah</h3>
            </div>
            <g:form action="confirmEdit" class="form-horizontal" method="POST" name="form1">
                <div class="box-body">
                    <property:alert message="${flash.message}" type="success"/>
                    <property:alert message="${flash.error}" type="danger"/>
                    <div class="form-group">
                        <label for="tfName" class="col-sm-3 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="id" value="${detail.id}" />
                            <input type="text" name="name" class="form-control" id="tfName" maxlength="200" placeholder="Name" value="${detail.name}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tfDescription" class="col-sm-3 control-label">Deskripsi:</label>
                        <div class="col-sm-8">
                            <input type="text" name="description" class="form-control" id="tfDescription" maxlength="200" placeholder="Description" value="${detail.description}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Ingatkan setiap tanggal:</label>
                        <div class="col-sm-8">
                            <input type="number" name="reminderDay" class="form-control" placeholder="1-28" maxlength="2" value="${detail.reminderDay}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Pesan:</label>
                        <div class="col-sm-8">
                            <textarea rows="4" cols="50" name="message" class="form-control" placeholder="Message" maxlength="500" required>${detail.message}</textarea>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <g:link controller="reminderList" action="index" class="btn btn-default">Batal</g:link>
                    <button type="submit" class="btn btn-info pull-right">Konfirmasi</button>
                </div>
            </g:form>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $('#form1').validate({
                rules: {
                    reminderDay: {
                        required: true,
                        greaterThanZero: true
                    },
                    deadline: {
                        required: true,
                        greaterThanZero: true
                    }
                },
                submitHandler: function(form) {
                    $.blockUI({ message: 'Sedang diproses, harap menunggu.' });
                    form.submit();
                }
            });
        });
    </script>
</body>
</html>

grails-app/views/reminderList/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Reminder List</title>
</head>

<body>
<section class="content-header">
    <property:pageHeader title="Daftar Pengingat" description="Tambah dan Ubah Pengingat" />
    <ol class="breadcrumb">
        <li>Maintenance</li>
        <li class="active"><i class="fa fa-info"></i> Reminder List</li>
    </ol>
</section>

<section class="content container-fluid">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Daftar Pengingat</h3>
        </div>
        <div class="box-body">
            <property:alert message="${flash.message}" type="success"/>
            <property:alert message="${flash.error}" type="danger"/>

            <g:link controller="reminderList" action="create" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Tambah Pengingat</g:link>

            <table class="table table-striped table-bordered table-hover" id="dataTables-obj" style="width: 100%">

            </table>
        </div>
        <div class="box-footer">
        </div>
    </div>
</section>

<script>
    var detailUrl = '${g.createLink(controller:'reminderList',action:'detail')}';

    $(document).ready(function(){
        $('#dataTables-obj').dataTable({
            "language": {
                "paginate": {
                    "previous": "Sebelumnya",
                    "next": "Berikutnya"
                },
                "info": "Menampilkan halaman _PAGE_ dari _PAGES_",
                "emptyTable": "Data tidak ditemukan"
            },
            "bLengthChange": false,
            "bFilter": false,
            "bServerSide": true,
            "bProcessing": true,
            "sPaginationType": "simple_numbers",
            "sAjaxSource": '${g.createLink(controller:'reminderList',action:'listDatatable')}',
            "aoColumns": [
                { "mData": "name", "sTitle":"Nama", "mRender":
                        function(data, type, full){
                            return "<a href='"+detailUrl+"/"+full.id+"'>"+full.name+"</a>";
                        }
                },
                { "mData": "description", "sTitle":"Deskripsi" },
                { "mData": "createdDate", "sTitle":"Dibuat Tanggal" },
                { "mData": "createdBy", "sTitle":"Dibuat Oleh" },
                { "mData": "status", "sTitle":"Status" }
            ]
        });
    });

</script>
</body>
</html>