grails-app/controllers/com/property/controllers/admin/UserSalesController.groovy
package com.property.controllers.admin

import com.model.AppConstants
import com.model.property.Property
import com.model.property.PropertyDeal
import com.model.property.PropertyPayment
import com.model.security.ResetPasswordToken
import com.model.security.Role
import com.model.security.User
import com.model.security.UserInfo
import com.model.security.UserRole
import com.property.utils.ControllerUtil
import grails.converters.JSON
import grails.web.mapping.LinkGenerator
import org.apache.commons.lang.exception.ExceptionUtils

import java.text.SimpleDateFormat



class UserSalesController {

    LinkGenerator grailsLinkGenerator
    def mailService

    def index() {
        log.debug "IN index... $params"
    }

    def resetPassword(){
        log.debug "IN resetPassword... $params"
        def user = User.get(params.id)
        def userName = UserInfo.findByUser(user)?.name?:user?.username
        //generate token
        def token = UUID.randomUUID().toString().replaceAll("-","")
        ResetPasswordToken.withTransaction { status ->
            try{
                def obj = ResetPasswordToken.findByEmail(user.username)
                if(obj!=null){
                    obj.delete()
                }
                obj = new ResetPasswordToken()
                obj.email = user.username
                obj.token = token
                obj.createdTime = new Date().time
                obj.expiredTime = 3600
                obj.save()

                def tokenLink = grailsLinkGenerator.serverBaseURL.concat(g.createLink(controller: 'auth', action: 'changePassword', params: [id: token]))

                log.debug("sending email emailPassword")
                mailService.sendMail {
                    to user.username
                    from "support@warga-kita.com"
                    subject "Warga Kita Reset Password"
                    html view: "emailPassword", model: [userName: userName?:"", tokenLink: tokenLink]
                }
                flash.message = "Email telah dikirim"
            } catch (Exception e) {
                log.error ExceptionUtils.getStackTrace(e)
                status.setRollbackOnly()
                flash.error = "Server bermasalah, coba lagi beberapa saat."
            }
        }
        redirect(action: 'detailUser', params:params)
    }

    def listDatatable(){
        def columns = ['i.user.username', 'i.name', 'i.phoneNo']
        def query = "SELECT i FROM UserRole ur, UserInfo i WHERE ur.role.authority = :role and i.user.username = ur.user.username"
        def queryCount = "SELECT count(i) FROM UserRole ur, UserInfo i WHERE ur.role.authority = :role and i.user.username = ur.user.username"
        def queryParams = [role:AppConstants.ROLE_SALES]
        def result = ControllerUtil.parseDatatablesQuery(UserInfo.class, params, query, queryCount, queryParams, columns)

        def objs = result.objs
        def aaData = []
        objs.each{ obj ->
            def det = [id:obj.user.id, username: obj.user.username, name: obj.name, phoneNo: obj.phoneNo]
            det.totalDealProposed = PropertyDeal.executeQuery("SELECT count(id) FROM PropertyDeal WHERE createdBy = :userId",[userId:obj.id])[0]
            def propIdList = Property.executeQuery("FROM Property WHERE sales.user.id = :userId",[userId:obj.user.id]).collect{it.id}
            if(propIdList.size()>0) {
                det.totalDealSecured = propIdList.size()
                det.totalRevenue = PropertyPayment.executeQuery("SELECT sum(salesCommission) FROM PropertyPayment WHERE propertyId IN :propIdList", [propIdList: propIdList])[0]?:"0"
            } else {
                det.totalDealSecured = 0
                det.totalRevenue = 0
            }
            aaData.add(det)
        }
        result.aaData = aaData
        result.objs = null
        render result as JSON
    }

    def detail(){
        log.debug "IN detail... $params"
        def user = User.get(params.id)
        def userInfo = UserInfo.findByUser(user)
        def result = [id:params.id, username:userInfo.user.username, name:userInfo.name, phoneNo: userInfo.phoneNo,
                      bankAccount: userInfo.bankAccount, bankName: userInfo.bankName]

        result.totalDealProposed = PropertyDeal.executeQuery("SELECT count(id) FROM PropertyDeal WHERE createdBy = :userId",[userId:user.id])[0]
        def propIdList = Property.executeQuery("FROM Property WHERE sales.user.id = :userId",[userId:user.id]).collect{it.id}
        if(propIdList.size()>0){
            result.totalDealSecured = propIdList.size()
        } else {
            result.totalDealSecured = 0
            result.totalRevenue = 0
        }

        def propList = []
        def sdf = new SimpleDateFormat("yyyy-MM-dd")
        Property.executeQuery("FROM Property WHERE sales.user.id = :userId",[userId:user.id]).each { prop ->
            def det = [name:prop.name, address:prop.address, developer: prop.developer, totalUnit: prop.totalUnit, fee:prop.fee]
            if(prop.expiryDate!=null){
                det.expiryDate = sdf.format(prop.expiryDate)
            }
            propList.add(det)
        }

        [user:result, propList:propList]
    }

    def delete(){
        log.debug "IN delete... $params"
        def isError = false, message = ''
        def user = User.get(params.id)
        if(user!=null){
            User.withTransaction { status ->
                try {
                    UserRole.findAllByUser(user).each{
                        it.delete()
                    }
                } catch (Exception e){
                    log.error ExceptionUtils.getStackTrace(e)
                    status.setRollbackOnly()
                    isError = true
                    message = "System error"
                }
            }
        } else {
            message = "Sales tidak ditemukan"
            redirect(action: 'index')
        }
        if(isError) {
            flash.error = message
            redirect(action: 'detailUser', params:params)
        } else {
            flash.message = "Sales berhasil dihapus"
            redirect(action: 'index')
        }
    }

    def create(){
        log.debug "IN create... $params"
        if(params._action_create == 'Back'){
            [user: [username:params.username, name:params.name, phoneNo:params.phoneNo, bankAccount: params.bankAccount, bankName: params.bankName]]
        } else {
            [user:[:]]
        }
    }

    def confirmAdd(){
        log.debug "IN confirmAdd... $params"
        def username = params.username
        def name = params.name
        def phoneNo = params.phoneNo
        def bankName = params.bankName
        def bankAccount = params.bankAccount

        if(!ControllerUtil.hasValue(username) || !ControllerUtil.hasValue(name)){
            flash.error = "Silakan isi semua data yang diperlukan"
            params._action_create = 'Back'
            redirect(action: 'create', params:params)
            return
        }

        def result = [username:username, name:name, phoneNo:phoneNo, bankName:bankName, bankAccount:bankAccount]
        def user = User.findByUsername(username)
        if(user==null){
            result.action = 'Create Sales'
            result.stage = 'Confirm'
            result.actionType = 'add'
            render view:'confirm', model: [user:result]
        } else {
            flash.error = "User dengan nama ${username} sudah ada"
            params._action_create = 'Back'
            redirect(action: 'create', params:params)
        }
    }

    def submitAdd(){
        log.debug "IN submitAdd... $params"
        def username = params.username
        def name = params.name
        def phoneNo = params.phoneNo
        def bankName = params.bankName
        def bankAccount = params.bankAccount

        def result = [username:username, name:name, phoneNo: phoneNo, bankName:bankName, bankAccount:bankAccount,
                      actionType: 'add', action:'Create Sales']
        def isError = false
        def message = ""

        def user = User.findByUsername(username)
        if(user==null){
            User.withTransaction { status ->
                try {
                    String randomString = org.apache.commons.lang.RandomStringUtils.random(9, true, true)

                    user = new User()
                    user.username = username
                    user.password = randomString
                    user.save(flush: true)

                    def role = Role.findByAuthority(AppConstants.ROLE_SALES)
                    new UserRole(user: user, role: role).save(flush: true)

                    def userInfo = new UserInfo()
                    userInfo.user = user
                    userInfo.name = name
                    userInfo.phoneNo = phoneNo
                    userInfo.bankAccount = bankAccount
                    userInfo.bankName = bankName
                    userInfo.save(flush: true)

                    log.debug("sending email emailNewUser")
                    mailService.sendMail {
                        to user.username
                        from "support@warga-kita.com"
                        subject "Warga Kita User Password"
                        html view: "emailNewUser", model: [userName: name, password: randomString]
                    }
                } catch (Exception e){
                    log.error ExceptionUtils.getStackTrace(e)
                    status.setRollbackOnly()
                    isError = true
                    message = "System error"
                }
            }
        } else {
            message = "User with username ${username} already exists"
        }
        if(isError) {
            result.stage = 'Confirm'
            flash.error = message
        } else {
            result.stage = 'Result'
            flash.message = "Sales berhasil ditambahkan"
        }
        render view: 'confirm', model: [user:result]
    }

    def edit(){

grails-app/views/userSales/confirm.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>${user.stage} ${user.action}</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Pengaturan Team Sales" description="Tambah dan Edit Team Sales" />
        <ol class="breadcrumb">
            <li><i class="fa fa-users"></i> <g:link controller="userSales" action="index"> Manage Sales</g:link></li>
            <li>${user.action}</li>
            <li class="active">${user.stage}</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">${user.stage}</h3>
            </div>
            <g:form action="${user.actionType=='add'?'submitAdd':'submitEdit'}" class="form-horizontal" method="POST">
                <div class="box-body">
                    <property:alert message="${flash.message}" type="success" title="${user.action}"/>
                    <property:alert message="${flash.error}" type="danger" title="${user.action}"/>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="id" value="${user.id}" />
                            <input type="hidden" name="username" value="${user.username}" />
                            <p class="form-control-static">${user.username}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="name" value="${user.name}" />
                            <p class="form-control-static">${user.name}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">No Telepon:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="phoneNo" value="${user.phoneNo}" />
                            <p class="form-control-static">${user.phoneNo}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama Bank:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="bankName" value="${user.bankName}" />
                            <p class="form-control-static">${user.bankName}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">No Rekening Bank:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="bankAccount" value="${user.bankAccount}" />
                            <p class="form-control-static">${user.bankAccount}</p>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <g:if test="${user.stage == 'Confirm'}">
                        <button type="button" onclick="window.history.back();" class="btn btn-default">Kembali</button>
                        <button type="submit" onclick="$.blockUI({ message: 'Sedang diproses, harap menunggu.' });" class="btn btn-info pull-right">Simpan</button>
                    </g:if>
                    <g:else>
                        <g:link controller="userSales" action="index" class="btn btn-success pull-right">Selesai</g:link>
                    </g:else>
                </div>
            </g:form>
        </div>
    </section>
</body>
</html>

grails-app/views/userSales/create.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Tambah Sales</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Pengaturan Team Sales" description="Tambah dan Edit Team Sales" />
        <ol class="breadcrumb">
            <li><i class="fa fa-users"></i> <g:link controller="userSales" action="index"> Manage Sales</g:link></li>
            <li class="active">Create Property Sales</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Tambah Sales Properti</h3>
            </div>
            <g:form action="confirmAdd" class="form-horizontal" method="POST" name="form1">
                <div class="box-body">
                    <property:alert message="${flash.message}" type="success"/>
                    <property:alert message="${flash.error}" type="danger"/>
                    <div class="form-group">
                        <label for="tfUsername" class="col-sm-2 control-label">Email:</label>
                        <div class="col-sm-8">
                            <input type="email" maxlength="50" name="username" class="form-control" id="tfUsername" placeholder="Email" value="${user.username}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tfName" class="col-sm-2 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <input type="text" maxlength="200" name="name" class="form-control" id="tfName" placeholder="Name" value="${user.name}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tfPhoneNo" class="col-sm-2 control-label">No Telepon:</label>
                        <div class="col-sm-8">
                            <input type="number" maxlength="20" name="phoneNo" class="form-control" id="tfPhoneNo" placeholder="Phone No" value="${user.phoneNo}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama Bank:</label>
                        <div class="col-sm-8">
                            <input maxlength="200" name="bankName" class="form-control" placeholder="Bank Name" value="${user.bankName}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">No Rekening Bank:</label>
                        <div class="col-sm-8">
                            <input maxlength="200" name="bankAccount" class="form-control" placeholder="Bank Account" value="${user.bankAccount}">
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <g:link controller="userSales" action="index" class="btn btn-default">Batal</g:link>
                    <button type="submit" class="btn btn-info pull-right">Konfirmasi</button>
                </div>
            </g:form>
        </div>
    </section>

    <script>
        $(document).ready(function(){
            $("#form1").validate({
                submitHandler: function(form) {
                    $.blockUI({ message: 'Sedang diproses, harap menunggu.' });
                    form.submit();
                }
            });
        });
    </script>
</body>
</html>

grails-app/views/userSales/detail.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Detail Sales</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Pengaturan Team Sales" description="Tambah dan Edit Team Sales" />
        <ol class="breadcrumb">
            <li><i class="fa fa-users"></i> <g:link controller="userSales" action="index"> Manage Sales</g:link></li>
            <li class="active">Detail Sales</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Detail</h3>
            </div>
            <div class="box-body" id="testBody">
                <property:alert message="${flash.message}" type="success"/>
                <property:alert message="${flash.error}" type="danger"/>
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Email:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${user.username}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${user.name}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">No Telepon:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${user.phoneNo}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama Bank:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${user.bankName}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">No Rekening Bank:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${user.bankAccount}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Deal Proposed:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${user.totalDealProposed}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Secured Deal:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${user.totalDealSecured}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Revenue:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${user.totalRevenue}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-header with-border">
                <h3 class="box-title">Secured Property Deals</h3>
            </div>
            <div class="box-body">
                <table class="table table-striped table-bordered table-hover" id="dataTables-property" style="width: 100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Developer</th>
                            <th>Address</th>
                            <th>Total Unit</th>
                            <th>Fee</th>
                            <th>Expiry Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <g:each in="${propList}" var="obj">
                            <tr>
                                <td>${obj.name}</td>
                                <td>${obj.developer}</td>
                                <td>${obj.address}</td>
                                <td>${obj.totalUnit}</td>
                                <td>${obj.fee}</td>
                                <td>${obj.expiryDate}</td>
                            </tr>
                        </g:each>
                    </tbody>
                </table>
            </div>
            <div class="box-footer">
                <g:link controller="userSales" action="index" class="btn btn-default">Kembali</g:link>
                <div class="pull-right">
                    <g:link controller="userSales" action="edit" params="[id:user.id]" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</g:link>
                    <g:link controller="userSales" action="resetPassword" params="[id:user.id]" class="btn btn-warning"><i class="fa fa-save"></i> Reset Password</g:link>
                    <button type="button" onclick="confirmDelete()" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                </div>
            </div>
        </div>
    </section>

    <g:form name="formDelete" controller="userSales" action="delete" method="POST">
        <input type="hidden" name="id" value="${user.id}" />
    </g:form>

    <script>
        $(document).ready(function(){
            $('#dataTables-property').dataTable({
                "language": {
                    "paginate": {
                        "previous": "Sebelumnya",
                        "next": "Berikutnya"
                    },
                    "info": "Menampilkan halaman _PAGE_ dari _PAGES_",
                    "emptyTable": "Data tidak ditemukan"
                },
                "bLengthChange": false,
                "bPaginate": true,
                "bFilter": false,
                "bInfo": false
            });
        });

        function confirmDelete(){
            vex.dialog.confirm({
                message: 'Apakah anda yakin untuk menghapus data user ini?',
                callback: function (value) {
                    if (value) {
                        $('#formDelete').submit();
                    }
                }
            });
        }
    </script>
</body>
</html>

grails-app/views/userSales/edit.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Edit Sales</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Pengaturan Team Sales" description="Tambah dan Edit Team Sales" />
        <ol class="breadcrumb">
            <li><i class="fa fa-users"></i> <g:link controller="userSales" action="index"> Manage Sales</g:link></li>
            <li class="active">Edit Sales</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Ubah</h3>
            </div>
            <g:form action="confirmEdit" class="form-horizontal" method="POST" name="form1">
                <div class="box-body">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Email:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="id" value="${user.id}" />
                            <input type="hidden" name="username" value="${user.username}" />
                            <p class="form-control-static">${user.username}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tfName" class="col-sm-2 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <input type="text" maxlength="200" name="name" class="form-control" id="tfName" placeholder="Name" value="${user.name}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tfPhoneNo" class="col-sm-2 control-label">No Telepon:</label>
                        <div class="col-sm-8">
                            <input type="number" maxlength="20" name="phoneNo" class="form-control" id="tfPhoneNo" placeholder="Phone No" value="${user.phoneNo}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama Bank:</label>
                        <div class="col-sm-8">
                            <input maxlength="200" name="bankName" class="form-control" placeholder="Bank Name" value="${user.bankName}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">No Rekening Bank:</label>
                        <div class="col-sm-8">
                            <input maxlength="200" name="bankAccount" class="form-control" placeholder="Bank Account" value="${user.bankAccount}">
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <g:link controller="userSales" action="index" class="btn btn-default">Batal</g:link>
                    <button type="submit" class="btn btn-info pull-right">Konfirmasi</button>
                </div>
            </g:form>
        </div>
    </section>

    <script>
        $(document).ready(function(){
           $('#form1').validate({
               submitHandler: function(form) {
                   $.blockUI({ message: 'Sedang diproses, harap menunggu.' });
                   form.submit();
               }
           });
        });
    </script>
</body>
</html>

grails-app/views/userSales/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Manage Sales</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Pengaturan Team Sales" description="Tambah dan Edit Team Sales" />
        <ol class="breadcrumb">
            <li class="active"><i class="fa fa-users"></i> Manage Sales</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Daftar Properti Sales</h3>
            </div>
            <div class="box-body">
                <property:alert message="${flash.message}" type="success"/>
                <property:alert message="${flash.error}" type="danger"/>

                <g:link controller="userSales" action="create" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Create Sales</g:link>

                <table class="table table-striped table-bordered table-hover" id="dataTables-users" style="width: 100%">

                </table>
            </div>
            <div class="box-footer">
            </div>
        </div>
    </section>

    <script>
        var detailUserUrl = '${g.createLink(controller:'userSales',action:'detail')}';

        $(document).ready(function(){
            $('#dataTables-users').dataTable({
                "language": {
                    "paginate": {
                        "previous": "Sebelumnya",
                        "next": "Berikutnya"
                    },
                    "info": "Menampilkan halaman _PAGE_ dari _PAGES_",
                    "emptyTable": "Data tidak ditemukan"
                },
                "bLengthChange": false,
                "bFilter": false,
                "bServerSide": true,
                "bProcessing": true,
                "sPaginationType": "simple_numbers",
                "sAjaxSource": '${g.createLink(controller:'userSales',action:'listDatatable')}',
                "columnDefs": [
                    { "orderable": false, "targets": 3 },
                    { "orderable": false, "targets": 4 },
                    { "orderable": false, "targets": 5 }
                ],
                "aoColumns": [
                    { "mData": "username", "sTitle":"Email", "mRender":
                            function(data, type, full){
                                return "<a href='"+detailUserUrl+"/"+full.id+"'>"+full.username+"</a>";
                            }},
                    { "mData": "name", "sTitle":"Nama" },
                    { "mData": "phoneNo", "sTitle":"No Telepon" },
                    { "mData": "totalDealProposed", "sTitle":"Deal Proposed" },
                    { "mData": "totalDealSecured", "sTitle":"Deal Secured" },
                    { "mData": "totalRevenue", "sTitle":"Total Revenue" }
                ]
            });
        });
    </script>
</body>
</html>