grails-app/controllers/com/property/controllers/pm/ManageFacilityBookingController.groovy
package com.property.controllers.pm

import com.model.AppConstants
import com.model.general.CodeSequence
import com.model.general.FacilityBooking
import com.model.general.PropertyAdminProperty
import com.model.general.UserMobileUnit
import com.model.property.Facility
import com.model.security.User
import com.model.security.UserInfo
import com.model.security.UserMobile
import com.property.utils.ControllerUtil
import grails.converters.JSON
import org.apache.commons.lang.exception.ExceptionUtils

import java.text.SimpleDateFormat



class ManageFacilityBookingController {
    def bookingService
    def springSecurityService

    def index() {
        log.debug "IN index... $params"
        def pmId = springSecurityService.principal?.pmId
        def facilityList = Facility.executeQuery("FROM Facility WHERE area.property.propertyManager.pmId = :pmId",[pmId:pmId])
        def statusList = AppConstants.getFacilityBookingStatusList()
        [facilityList:facilityList, facilityId:params.facilityId, status:params.status, code:params.code, statusList:statusList]
    }

    def listDatatable(){
        def propIdList = PropertyAdminProperty.executeQuery("FROM PropertyAdminProperty WHERE propertyAdmin.id = :currentUser",
                [currentUser:springSecurityService.principal.id]).collect{ it.property.id }
        if(propIdList.size()==0){
            propIdList.add("")
        }
        def columns = ['facility.name', 'code', 'startDate, startTime', 'startDate, startTime', 'description', 'status', '']
        def baseQuery = "FROM FacilityBooking " +
                "WHERE lower(code) like lower(:code) " +
                "AND facility.id like :facilityId " +
                "AND status like :status " +
                "AND facility.area.property.id in :propIdList "
        def query = baseQuery
        def queryCount = "SELECT count(id) " + baseQuery

        def facilityId = params.facilityId?:'%'
        def code = params.code?ControllerUtil.appendWc(params.code):'%'
        def status = params.status?:'%'
        def queryParams = [facilityId:facilityId, code:code, propIdList:propIdList, status:status]
        def result = ControllerUtil.parseDatatablesQuery(FacilityBooking.class, params, query, queryCount, queryParams, columns)

        def objs = result.objs
        def aaData = []
        def sdfDate = new SimpleDateFormat("yyyy-MM-dd")
        def sdfTime = new SimpleDateFormat("HH:mm")
        objs.each{ obj ->
            def userName = UserMobile.findByEmail(obj.createdBy)?.name?:UserInfo.findByUser(User.get(obj.createdBy))?.name
            aaData.add([id:obj.id, facilityName: obj.facility.name, userName: userName,
                        bookDate: sdfDate.format(obj.startDate), bookTime: "${sdfTime.format(obj.startTime)}-${sdfTime.format(obj.endTime)}",
                        code:obj.code, startDate:sdfDate.format(obj.startDate), status:obj.status])
        }
        result.aaData = aaData
        result.objs = null
        render result as JSON
    }

    def detail(){
        log.debug "IN detail... $params"
        def propList = PropertyAdminProperty.executeQuery("FROM PropertyAdminProperty WHERE propertyAdmin.id = :currentUser",
                [currentUser:springSecurityService.principal.id]).collect{ it.property }
        def prop = propList.get(0)
        def objs = FacilityBooking.executeQuery("FROM FacilityBooking WHERE facility.area.property.id = :propId AND id = :id", [propId:prop.id, id:params.id])
        if(objs.size()>0) {
            def sdfDate = new SimpleDateFormat("yyyy-MM-dd")
            def sdfTime = new SimpleDateFormat("HH:mm")
            def obj = objs.get(0)
            def result = [id: params.id, code: obj.code, facilityName:obj.facility.name, status: obj.status, description:obj.description,
                          bookDate: sdfDate.format(obj.startDate), bookTime: "${sdfTime.format(obj.startTime)}-${sdfTime.format(obj.endTime)}"]
            def userMobile = UserMobile.findByEmail(obj.createdBy)
            if(userMobile!=null){
                result.fromMobile = true
                result.unit = UserMobileUnit.findByUserMobile(userMobile)?.unit?.name
                result.name = userMobile.name
                result.email = userMobile.email
                result.phoneNo = userMobile.phoneNo
            } else {
                result.fromMobile = false
                result.name = UserInfo.findByUser(User.get(obj.createdBy))?.name
            }
            result.isOpen = AppConstants.BOOKING_STATUS_OPEN.equals(obj.status)
            result.isNew = AppConstants.BOOKING_STATUS_NEW.equals(obj.status)
            [detail: result]
        } else {
            flash.error = "Booking tidak ditemukan"
            redirect(action: 'index')
        }
    }

    def approve(){
        log.debug "IN approve... $params"
        def propIdList = PropertyAdminProperty.executeQuery("FROM PropertyAdminProperty WHERE propertyAdmin.id = :currentUser",
                [currentUser:springSecurityService.principal.id]).collect{ it.property.id }

        def fbs = FacilityBooking.executeQuery("FROM FacilityBooking WHERE id = :id AND facility.area.property.id IN :propIdList",
                [id:params.id, propIdList:propIdList])
        if(fbs.size()==0){
            flash.error = "Data tidak ditemukan"
        } else {
            def fb = fbs.get(0)
            def isAvailable = bookingService.isBookingAvailable(fb.facility.id, fb.startDate, fb.startTime, fb.endTime)
            if(!isAvailable){
                flash.error = "Periode waktu sudah dipakai."
            } else {
                FacilityBooking.withTransaction { status ->
                    try {
                        fb.updatedBy = springSecurityService.principal.id
                        fb.status = AppConstants.BOOKING_STATUS_OPEN
                        fb.save(flush: true)
                        flash.message = "Permintaan ${fb.code} berhasil disetujui."
                    } catch (Exception e) {
                        log.error ExceptionUtils.getStackTrace(e)
                        status.setRollbackOnly()
                        flash.error = "Server bermasalah, coba lagi beberapa saat."
                    }
                }
            }
        }
        redirect(action:'index', params:[facilityId:params.facilityId, status:params.status, code:params.code])
    }

    def cancel(){
        log.debug "IN cancel... $params"
        def propIdList = PropertyAdminProperty.executeQuery("FROM PropertyAdminProperty WHERE propertyAdmin.id = :currentUser",
                [currentUser:springSecurityService.principal.id]).collect{ it.property.id }

        def fbs = FacilityBooking.executeQuery("FROM FacilityBooking WHERE id = :id AND facility.area.property.id IN :propIdList",
                [id:params.id, propIdList:propIdList])
        if(fbs.size()==0){
            flash.error = "Data tidak ditemukan"
        } else {
            def fb = fbs.get(0)
            FacilityBooking.withTransaction { status ->
                try{
                    fb.updatedBy = springSecurityService.principal.id
                    fb.status = AppConstants.BOOKING_STATUS_CANCELED
                    fb.save(flush:true)
                    flash.message = "Permintaan ${fb.code} berhasil dibatalkan"
                } catch (Exception e){
                    log.error ExceptionUtils.getStackTrace(e)
                    status.setRollbackOnly()
                    flash.error = "Server bermasalah, coba lagi beberapa saat."
                }
            }
        }
        redirect(action:'index', params:[facilityId:params.facilityId, status:params.status, code:params.code])
    }

    def reject(){
        log.debug "IN reject... $params"
        def propIdList = PropertyAdminProperty.executeQuery("FROM PropertyAdminProperty WHERE propertyAdmin.id = :currentUser",
                [currentUser:springSecurityService.principal.id]).collect{ it.property.id }

        def fbs = FacilityBooking.executeQuery("FROM FacilityBooking WHERE id = :id AND facility.area.property.id IN :propIdList",
                [id:params.id, propIdList:propIdList])
        if(fbs.size()==0){
            flash.error = "Data tidak ditemukan"
        } else {
            def fb = fbs.get(0)
            FacilityBooking.withTransaction { status ->
                try{
                    fb.updatedBy = springSecurityService.principal.id
                    fb.status = AppConstants.BOOKING_STATUS_REJECTED
                    fb.save(flush:true)
                    flash.message = "Permintaan ${fb.code} berhasil ditolak"
                } catch (Exception e){
                    log.error ExceptionUtils.getStackTrace(e)
                    status.setRollbackOnly()
                    flash.error = "Server bermasalah, coba lagi beberapa saat."
                }
            }
        }
        redirect(action:'index', params:[facilityId:params.facilityId, status:params.status, code:params.code])
    }
}

grails-app/views/manageFacilityBooking/detail.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Detail Booking</title>
</head>

<body>
<section class="content-header">
    <property:pageHeader title="Persetujuan Fasilitas Umum" description="Setuju dan Tolak Permintaan Fasilitas Umum" />
    <ol class="breadcrumb">
        <li>Activity</li>
        <li class="active"><i class="fa fa-address-card"></i> Detail Booking</li>
    </ol>
</section>


<section class="content container-fluid">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Detail</h3>
        </div>
        <div class="box-body" id="testBody">
            <property:alert message="${flash.message}" type="success"/>
            <property:alert message="${flash.error}" type="danger"/>
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-2 control-label">Kode:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.code}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Fasilitas:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.facilityName}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Tanggal:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.bookDate}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Waktu:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.bookTime}</p>
                    </div>
                </div>
                <g:if test="${detail.fromMobile}">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Unit:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.unit}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.name}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Email:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.email}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">No HP:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.phoneNo}</p>
                        </div>
                    </div>
                </g:if>
                <g:else>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama:</label>
                        <div class="col-sm-8">
                            <p class="form-control-static">${detail.name}</p>
                        </div>
                    </div>
                </g:else>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Keterangan:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.description}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Status:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.status}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <g:link controller="manageFacilityBooking" action="index" class="btn btn-default">Kembali</g:link>
            <div class="pull-right">
                <g:if test="${detail.isNew}">
                    <button type="button" onclick="onApproveClick()" class="btn btn-primary"><i class="fa fa-check"></i> Setujui</button>
                    <button type="button" onclick="onRejectClick()" class="btn btn-danger"><i class="fa fa-times"></i> Tolak</button>
                </g:if>
                <g:if test="${detail.isOpen}">
                    <button type="button" onclick="onCancelClick()" class="btn btn-danger"><i class="fa fa-times"></i> Batal</button>
                </g:if>
            </div>
        </div>
    </div>
</section>

<g:form name="formApprove" action="approve" method="POST">
    <input type="hidden" name="id" value="${detail.id}" />
</g:form>

<g:form name="formCancel" action="cancel" method="POST">
    <input type="hidden" name="id" value="${detail.id}" />
</g:form>

<g:form name="formReject" action="reject" method="POST">
    <input type="hidden" name="id" value="${detail.id}" />
</g:form>

<script>
    var code = '${detail.code}';
    function onApproveClick(){
        vex.dialog.confirm({
            message: 'Apakah anda yakin untuk Menyetujui permintaan dengan kode: '+code+'?',
            callback: function (value) {
                if (value) {
                    $.blockUI({ message: 'Sedang diproses, harap menunggu.' });
                    $('#formApprove').submit();
                }
            }
        });
    }

    function onCancelClick(){
        vex.dialog.confirm({
            message: 'Apakah anda yakin untuk Membatalkan permintaan dengan kode: '+code+'?',
            callback: function (value) {
                if (value) {
                    $.blockUI({ message: 'Sedang diproses, harap menunggu.' });
                    $('#formCancel').submit();
                }
            }
        });
    }

    function onRejectClick(){
        vex.dialog.confirm({
            message: 'Apakah anda yakin untuk Menolak permintaan dengan kode: '+code+'?',
            callback: function (value) {
                if (value) {
                    $.blockUI({ message: 'Sedang diproses, harap menunggu.' });
                    $('#formReject').submit();
                }
            }
        });
    }
</script>
</body>
</html>

grails-app/views/manageFacilityBooking/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Manage Booking</title>
</head>

<body>
<section class="content-header">
    <property:pageHeader title="Persetujuan Fasilitas Umum" description="Setuju dan Tolak Permintaan Fasilitas Umum" />
    <ol class="breadcrumb">
        <li>Activity</li>
        <li class="active"><i class="fa fa-address-card"></i> Manage Booking</li>
    </ol>
</section>

<section class="content container-fluid">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Daftar Pesanan Fasilitas Umum</h3>
        </div>
        <div class="box-body">
            <property:alert message="${flash.message}" type="success"/>
            <property:alert message="${flash.error}" type="danger"/>

            <g:link controller="facilityBooking" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Tambah Pesanan Fasilitas Umum</g:link>

            <br style="clear:both" />

            <g:form action="index" class="form-horizontal" method="GET" style="margin-bottom: 20px;">
                <div class="form-group">
                    <label for="facilityList" class="col-sm-2 control-label">Fasilitas:</label>
                    <div class="col-sm-8">
                        <g:select id="facilityList" name='facilityId' value="${facilityId}"
                                  noSelection="${['':'Tampilkan Semua']}"
                                  from='${facilityList}' class="form-control select2"
                                  optionKey="id" optionValue="name"></g:select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="statusList" class="col-sm-2 control-label">Status:</label>
                    <div class="col-sm-8">
                        <g:select id="statusList" name='status' value="${status}"
                                  noSelection="${['':'Tampilkan Semua']}"
                                  from='${statusList}' class="form-control select2"></g:select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="tfCode" class="col-sm-2 control-label">Kode:</label>
                    <div class="col-sm-6">
                        <input type="text" name="code" class="form-control" id="tfCode" placeholder="Code" value="${code}">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-7">
                        <button type="submit" class="btn btn-info pull-right"><i class="fa fa-search"></i> Cari</button>
                    </div>
                </div>
            </g:form>

            <table class="table table-striped table-bordered table-hover" id="dataTables-bookings" style="width: 100%;">

            </table>
        </div>
        <div class="box-footer">
        </div>
    </div>
</section>

<g:form name="formApprove" action="approve" method="POST">
    <input type="hidden" name="facilityId" value="${facilityId}" />
    <input type="hidden" name="status" value="${status}" />
    <input type="hidden" name="code" value="${code}" />
</g:form>

<g:form name="formCancel" action="cancel" method="POST">
    <input type="hidden" name="facilityId" value="${facilityId}" />
    <input type="hidden" name="status" value="${status}" />
    <input type="hidden" name="code" value="${code}" />
</g:form>

<g:form name="formReject" action="reject" method="POST">
    <input type="hidden" name="facilityId" value="${facilityId}" />
    <input type="hidden" name="status" value="${status}" />
    <input type="hidden" name="code" value="${code}" />
</g:form>

<script>
    var detailBookingUrl = '${g.createLink(controller:'manageFacilityBooking',action:'detail')}';
    var statusNew = '${com.model.AppConstants.BOOKING_STATUS_NEW}';
    var statusOpen = '${com.model.AppConstants.BOOKING_STATUS_OPEN}';

    $(document).ready(function(){
        $('#facilityList').select2();
        $('#statusList').select2();
        $('#dataTables-bookings').DataTable({
            "language": {
                "paginate": {
                    "previous": "Sebelumnya",
                    "next": "Berikutnya"
                },
                "info": "Menampilkan halaman _PAGE_ dari _PAGES_",
                "emptyTable": "Data tidak ditemukan"
            },
            "bLengthChange": false,
            "bFilter": false,
            "bServerSide": true,
            "bProcessing": true,
            "sPaginationType": "simple_numbers",
            "sAjaxSource": '${g.createLink(controller:'manageFacilityBooking',action:'listDatatable')}',
            "fnServerParams": function ( aoData ) {
                aoData.push( { "name": "facilityId", "value": $('#facilityList').val() } );
                aoData.push( { "name": "status", "value": $('#statusList').val() } );
                aoData.push( { "name": "code", "value": $('#tfCode').val() } );
            },
            "aoColumns": [
                { "mData": "code", "sTitle":"Kode" , "mRender":
                        function(data, type, full){
                            return "<a href='"+detailBookingUrl+"/"+full.id+"'>"+full.code+"</a>";
                        }
                },
                { "mData": "facilityName", "sTitle":"Fasilitas" },
                { "mData": "bookDate", "sTitle":"Tanggal Pesanan" },
                { "mData": "bookTime", "sTitle":"Waktu" },
                { "mData": "userName", "sTitle":"Nama" },
                { "mData": "status", "sTitle":"Status" },
                { "mData": "id", "sTitle":"", "mRender":
                        function(data, type, full){
                            if(full.status == statusNew){
                                return '<button class="btn btn-info" onclick="onApproveClick(\''+full.id+'\',\''+full.code+'\')"><i class="fa fa-check"></i> Setuju</button> ' +
                                        '<button class="btn btn-warning" onclick="onRejectClick(\''+full.id+'\',\''+full.code+'\')"><i class="fa fa-times"></i> Tolak</button>';
                            } else if(full.status == statusOpen){
                                return '<button class="btn btn-warning" onclick="onCancelClick(\''+full.id+'\',\''+full.code+'\')"><i class="fa fa-times"></i> Batal</button>';
                            } else {
                                return "";
                            }
                        }
                }
            ]
        });
    });

    function onApproveClick(id, code){
        vex.dialog.confirm({
            message: 'Apakah anda yakin untuk Menyetujui permintaan dengan kode: '+code+'?',
            callback: function (value) {
                if (value) {
                    $('#formApprove').append(
                            $('<input>').attr('type', 'hidden').attr('name', 'id').val(id)
                    );
                    $('#formApprove').submit();
                }
            }
        });
    }

    function onCancelClick(id, code){
        vex.dialog.confirm({
            message: 'Apakah anda yakin untuk Membatalkan permintaan dengan kode: '+code+'?',
            callback: function (value) {
                if (value) {
                    $('#formCancel').append(
                            $('<input>').attr('type', 'hidden').attr('name', 'id').val(id)
                    );
                    $('#formCancel').submit();
                }
            }
        });
    }

    function onRejectClick(id, code){
        vex.dialog.confirm({
            message: 'Apakah anda yakin untuk Menolak permintaan dengan kode: '+code+'?',
            callback: function (value) {
                if (value) {
                    $('#formReject').append(
                            $('<input>').attr('type', 'hidden').attr('name', 'id').val(id)
                    );
                    $('#formReject').submit();
                }
            }
        });
    }
</script>
</body>
</html>