grails-app/domain/com/model/property/PropertyDeal.groovy
package com.model.property

import com.model.Updatable
import com.model.maintenance.PropertyType
import com.model.security.UserInfo

class PropertyDeal extends Updatable{

    String id
    UserInfo sales
    String name
    String developer
    String address
    String description
    PropertyType propertyType
    Date startDate
    String status
    String attachment
    String attachmentName

    static mapping = {
        id type: 'string', generator: "uuid", name: 'id'
        name type: 'string', length: 200
        address type: 'string', length: 200
        developer type: 'string', length: 200
        description type: 'text'
        status type: 'string', length: 200
        attachment type: 'string', length: 200
        attachmentName type: 'string', length: 200
    }

    static constraints = {
        id nullable: true
        sales nullable: true
        name nullable: true
        developer nullable: true
        address nullable: true
        propertyType nullable: true
        status nullable: true
        description nullable: true
        attachment nullable: true
        attachmentName nullable: true
        startDate nullable: true
    }

}

grails-app/controllers/com/property/controllers/PropertyDealController.groovy
package com.property.controllers

import com.model.AppConstants
import com.model.maintenance.PropertyType
import com.model.maintenance.UnitType
import com.model.property.Property
import com.model.property.PropertyDeal
import com.model.property.PropertyRequest
import com.model.property.PropertyUnit
import com.model.security.User
import com.model.security.UserInfo
import com.model.security.UserRole
import com.property.utils.ControllerUtil
import grails.converters.JSON
import grails.plugin.springsecurity.annotation.Secured
import org.apache.commons.lang.exception.ExceptionUtils
import org.springframework.web.multipart.MultipartFile
import org.springframework.web.multipart.MultipartHttpServletRequest

import java.text.SimpleDateFormat


import com.bertramlabs.plugins.SSLRequired

@SSLRequired
@Secured(['ROLE_ADMIN','ROLE_SALES'])
class PropertyDealController {

    def springSecurityService

    def index() {
        log.debug "index..."
        [statusList:AppConstants.getDealStatusList(), status:params.status, name:params.name]
    }

    def listDatatable(){
        def columns = ['name', 'developer', 'address', 'propertyType.name', 'startDate', 'status']
        def baseQuery = "FROM PropertyDeal WHERE lower(name) like :name AND status like :status "

        def qName = ControllerUtil.hasValue(params.name)?"%${params.name.toLowerCase()}%".toString():"%"
        def qStatus = ControllerUtil.hasValue(params.status)?params.status:'%'

        def query = baseQuery
        def queryCount = "SELECT count(id) " + baseQuery
        def queryParams = [name: qName, status: qStatus]
        def result = ControllerUtil.parseDatatablesQuery(PropertyDeal.class, params, query, queryCount, queryParams, columns)

        def objs = result.objs
        def aaData = []
        def sdf = new SimpleDateFormat("yyyy-MM-dd")
        def currentDate = new Date()
        objs.each{ obj ->
            def det = [id:obj.id, name:obj.name, developer:obj.developer, address:obj.address, propertyType:obj?.propertyType?.name]
            if(obj.status.equals(AppConstants.DEAL_STATUS_IN_PROGRESS) && obj.startDate!=null){
                det.startDate = sdf.format(obj.startDate)
                use(groovy.time.TimeCategory) {
                    def duration = currentDate - obj.startDate
                    det.dayCount = duration.days
                }
            } else {
                det.startDate = ""
                det.dayCount = ""
            }
            det.status = AppConstants.getDealStatusName(obj.status)
            aaData.add(det)
        }
        result.aaData = aaData
        result.objs = null
        render result as JSON
    }

    def detail(){
        log.debug "IN detail... $params"
        def obj = PropertyDeal.get(params.id)
        if(obj!=null) {
            def sdf = new SimpleDateFormat("yyyy-MM-dd")
            def currentDate = new Date()
            def det = [id:obj.id, name:obj.name, developer:obj.developer, address:obj.address, propertyType:obj?.propertyType?.name,
                        attachment: obj.attachment, attachmentName: obj.attachmentName, description: obj.description, status:AppConstants.getDealStatusName(obj.status)]
            if(obj.status.equals(AppConstants.DEAL_STATUS_IN_PROGRESS) && obj.startDate!=null){
                det.startDate = sdf.format(obj.startDate)
                use(groovy.time.TimeCategory) {
                    def duration = currentDate - obj.startDate
                    det.dayCount = duration.days
                }
            }

            if(obj.createdDate!=null) {
                det.createdDate = sdf.format(obj.createdDate)
                def createdBy = User.get(obj.createdBy)
                if(createdBy!=null){
                    det.createdBy = UserInfo.findByUser(createdBy)?.name
                }
            }

            def currentUser = User.get(springSecurityService.principal.id)
            def userRole = UserRole.findByUser(currentUser)
            def isSales = userRole.role.authority == AppConstants.ROLE_SALES
            def isAdmin = userRole.role.authority == AppConstants.ROLE_ADMIN

            det.canEdit = AppConstants.DEAL_STATUS_NEW.equals(obj.status)
            det.canTake = isSales && AppConstants.DEAL_STATUS_NEW.equals(obj.status)
            if(AppConstants.DEAL_STATUS_IN_PROGRESS.equals(obj.status)){
                if(isAdmin || obj.sales?.user?.id == currentUser.id){
                    det.canRelease = true
                }
            }
            if(isSales && obj.sales?.user?.id == currentUser.id && AppConstants.DEAL_STATUS_IN_PROGRESS.equals(obj.status)){
                det.canSubmit = true
            }
            if(isAdmin && AppConstants.DEAL_STATUS_SUBMITTED.equals(obj.status)){
                det.canApprove = true
            }

            [detail: det]
        } else {
            flash.error = "Deal tidak ditemukan"
            redirect(action: 'index')
        }
    }

    def create(){
        log.debug "IN create... $params"
        def propertyTypeList = PropertyType.list()
        if(params._action_create == 'Back'){
            [detail: [name:params.name, developer:params.developer, address:params.address, propertyTypeId: params.propertyTypeId,
                    attachment:params.attachment, attachmentName: params.attachmentName, description: params.description],propertyTypeList:propertyTypeList]
        } else {
            [detail:[:],propertyTypeList:propertyTypeList]
        }
    }

    def confirmAdd(){
        log.debug "IN confirmAdd... $params"

        def name = params.name
        def developer = params.developer
        def address = params.address
        def propertyTypeId = params.propertyTypeId
        def description = params.description
        def attachment = params.attachment
        def attachmentName = params.attachmentName

        if(!ControllerUtil.hasValue(name)){
            flash.error = "Silakan isi semua data yang diperlukan"
            params._action_create = 'Back'
            redirect(action: 'create', params:params)
            return
        }

        def result = [name:name, developer:developer, address:address, propertyTypeId:propertyTypeId, description: description,
                      attachment:attachment, attachmentName:attachmentName, stage:'Confirm', actionType: 'add', action: 'Propose New Deal']
        if(ControllerUtil.hasValue(propertyTypeId)){
            def propertyType = PropertyType.get(propertyTypeId)
            result.propertyTypeName = propertyType?.name
        }
        render(view:'confirm', model: [detail: result])
    }

    def submitAdd(){
        log.debug "IN submitAdd... $params"

        def name = params.name
        def developer = params.developer
        def address = params.address
        def propertyTypeId = params.propertyTypeId
        def description = params.description
        def attachment = params.attachment
        def attachmentName = params.attachmentName

        if(!ControllerUtil.hasValue(name)){
            flash.error = "Silakan isi semua data yang diperlukan"
            params._action_create = 'Back'
            redirect(action: 'create', params:params)
            return
        }

        def result = [name:name, developer:developer, address:address, propertyTypeId:propertyTypeId, description: description,
                      attachment:attachment, attachmentName:attachmentName, actionType: 'add', action: 'Propose New Deal']
        def isError = false
        def message = ""

        def currentUser = User.get(springSecurityService.principal.id)
        def userRole = UserRole.findByUser(currentUser)
        def isAdmin = userRole.role.authority == AppConstants.ROLE_ADMIN

        PropertyDeal.withTransaction { status ->
            try {
                def obj = new PropertyDeal()
                obj.name = name
                obj.developer = developer
                obj.address = address
                if(ControllerUtil.hasValue(propertyTypeId)){
                    obj.propertyType = PropertyType.get(propertyTypeId)
                }
                obj.description = description
                if(!isAdmin){
                    obj.startDate = new Date()
                    obj.status = AppConstants.DEAL_STATUS_IN_PROGRESS
                    obj.sales = UserInfo.findByUser(currentUser)
                } else {
                    obj.status = AppConstants.DEAL_STATUS_NEW
                }
                obj.createdBy = currentUser.id

                if(ControllerUtil.hasValue(attachment)) {
                    //copy file from tmp
                    def srcFilePath = grailsApplication.config.getProperty("file.upload.path").concat("property${File.separator}tmp${File.separator}").concat(attachment)
                    def dstFilePath = grailsApplication.config.getProperty("file.upload.path").concat("property${File.separator}deal${File.separator}").concat(attachment)
                    def src = new File(srcFilePath)
                    def dst = new File(dstFilePath)
                    dst << src.bytes
                    if (src.exists()) src.delete()
                }
                obj.attachment = attachment
                obj.attachmentName = attachmentName

                result.propertyTypeName = obj.propertyType?.name

                obj.save(flush: true)
            } catch (Exception e){
                log.error ExceptionUtils.getStackTrace(e)
                status.setRollbackOnly()
                isError = true
                message = "System error"
            }
        }

        if(isError) {
            result.stage = 'Confirm'
            flash.error = message
        } else {
            result.stage = 'Result'
            flash.message = "Deal baru telah diajukan."
        }
        render view: 'confirm', model: [detail: result]
    }

    def edit(){
        log.debug "IN edit... $params"
        def obj = PropertyDeal.get(params.id)

grails-app/views/propertyDeal/approveDeal.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Approve Deal</title>
</head>

<body>
<section class="content-header">
    <property:pageHeader title="Properti Prospek" description="Usulan dan Pengajuan Properti Prospek" />
    <ol class="breadcrumb">
        <li><g:link controller="propertyDeal" action="index"><i class="fa fa-stamp"></i> Property Lead</g:link></li>
        <li class="active">Approve Lead</li>
    </ol>
</section>

<section class="content container-fluid">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Approval Information</h3>
        </div>
        <g:form action="confirmApproveDeal" class="form-horizontal" method="POST" name="form1">
            <div class="box-body">
                <property:alert message="${flash.message}" type="success"/>
                <property:alert message="${flash.error}" type="danger"/>

                <div class="form-group">
                    <label class="col-sm-2 control-label">Properti:</label>
                    <div class="col-sm-8">
                        <input type="hidden" name="id" value="${detail.id}" />
                        <p class="form-control-static">${detail.name}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Developer:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.developer}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Alamat:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.address}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Tipe:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.propertyType}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Keterangan:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.description}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Created:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.createdDate} by ${detail.createdBy}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Status:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.status}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Upload Gambar Properti:</label>
                    <div class="col-sm-8" style="padding-top: 7px">
                        <g:if test="${detail.attachment!=null && detail.attachment!=""}">
                            <g:link action="downloadFile" id="${detail.attachment}">${detail.attachmentName}</g:link>
                        </g:if>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Code:</label>
                    <div class="col-sm-8">
                        <input type="text" name="code" class="form-control" placeholder="Code" value="${detail.code}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Jumlah Unit:</label>
                    <div class="col-sm-8">
                        <input type="number" name="totalUnit" class="form-control" placeholder="Total Unit" value="${detail.totalUnit}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Fee:</label>
                    <div class="col-sm-8">
                        <input type="number" name="fee" class="form-control" placeholder="Fee" value="${detail.fee}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Expiry Tanggal:</label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="expiryDate" class="form-control" id="tfExpiryDate" value="${detail.expiryDate}" required>
                        </div>
                        <div id="expiryDate-error-msg"></div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <g:link action="index" class="btn btn-default">Batal</g:link>
                <button type="submit" class="btn btn-info pull-right">Konfirmasi</button>
            </div>
        </g:form>
    </div>
</section>
<script>
    $(document).ready(function() {
        $("#form1").validate({
            rules: {
                'expiryDate': {
                    required: true
                }
            },
            errorPlacement: function(error, element) {
                if (element.attr("name") == "expiryDate" ){
                    $('#expiryDate-error-msg').html('');
                    error.appendTo('#expiryDate-error-msg');
                } else {
                    error.insertAfter(element);
                }
            },
            success: function(label,element) {
                if ($(element).attr("name") == "expiryDate" ){
                    $('#expiryDate-error-msg').html('');
                } else {
                    $(label).remove();
                }
            },
            submitHandler: function(form) {
                $.blockUI({ message: 'Sedang diproses, harap menunggu.' });
                form.submit();
            }
        });
        $('#tfExpiryDate').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            "locale": {
                "format": "YYYY-MM-DD"
            },
            autoUpdateInput: false
        }, function(chosen_date) {
            $('#tfExpiryDate').val(chosen_date.format('YYYY-MM-DD'));
        });
    });
</script>
</body>
</html>

grails-app/views/propertyDeal/confirm.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>${detail.stage} ${detail.action}</title>
</head>

<body>
    <section class="content-header">
        <property:pageHeader title="Properti Prospek" description="Usulan dan Pengajuan Properti Prospek" />
        <ol class="breadcrumb">
            <li><g:link controller="propertyDeal" action="index"><i class="fa fa-stamp"></i> Property Lead</g:link></li>
            <li>${detail.action}</li>
            <li class="active">${detail.stage}</li>
        </ol>
    </section>

    <section class="content container-fluid">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">${detail.stage}</h3>
            </div>
            <g:form action="${detail.actionType=='add'?'submitAdd':'submitEdit'}" class="form-horizontal" method="POST">
                <div class="box-body">
                    <property:alert message="${flash.message}" type="success" title="${detail.action}"/>
                    <property:alert message="${flash.error}" type="danger" title="${detail.action}"/>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Properti:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="id" value="${detail.id}" />
                            <input type="hidden" name="name" value="${detail.name}" />
                            <p class="form-control-static">${detail.name}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Developer:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="developer" value="${detail.developer}" />
                            <p class="form-control-static">${detail.developer}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Alamat:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="address" value="${detail.address}" />
                            <p class="form-control-static">${detail.address}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Tipe:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="propertyTypeId" value="${detail.propertyTypeId}" />
                            <p class="form-control-static">${detail.propertyTypeName}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Keterangan:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="description" value="${detail.description}" />
                            <p class="form-control-static">${detail.description}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Upload Gambar Properti:</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="attachment" value="${detail.attachment}" />
                            <input type="hidden" name="attachmentName" value="${detail.attachmentName}" />
                            <g:if test="${detail.stage == 'Confirm'}">
                                <p class="form-control-static">${detail.attachmentName}</p>
                            </g:if>
                            <g:else>
                                <p class="form-control-static"><g:link action="downloadFile" id="${detail.attachment}">${detail.attachmentName}</g:link></p>
                            </g:else>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <g:if test="${detail.stage == 'Confirm'}">
                        <button type="button" onclick="window.history.back();" class="btn btn-default">Kembali</button>
                        <button type="submit" onclick="$.blockUI({ message: 'Sedang diproses, harap menunggu.' });" class="btn btn-info pull-right">Simpan</button>
                    </g:if>
                    <g:else>
                        <g:link controller="propertyDeal" action="index" class="btn btn-success pull-right">Selesai</g:link>
                    </g:else>
                </div>
            </g:form>
        </div>
    </section>
</body>
</html>

grails-app/views/propertyDeal/confirmApproveDeal.gsp
<%--
  Created by IntelliJ IDEA.
  User: enpee_000
  Date: 04/03/2018
  Time: 12:33
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Confirm Approve Deal</title>
</head>

<body>
<section class="content-header">
    <property:pageHeader title="Properti Prospek" description="Usulan dan Pengajuan Properti Prospek" />
    <ol class="breadcrumb">
        <li><g:link controller="propertyDeal" action="index"><i class="fa fa-stamp"></i> Property Lead</g:link></li>
        <li>Approve Lead</li>
        <li class="active">Confirm</li>
    </ol>
</section>

<section class="content container-fluid">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Approval Information</h3>
        </div>
        <g:form action="submitApproveDeal" class="form-horizontal" method="POST" name="form1">
            <div class="box-body">
                <property:alert message="${flash.message}" type="success"/>
                <property:alert message="${flash.error}" type="danger"/>

                <div class="form-group">
                    <label class="col-sm-2 control-label">Properti:</label>
                    <div class="col-sm-8">
                        <input type="hidden" name="id" value="${detail.id}" />
                        <p class="form-control-static">${detail.name}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Developer:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.developer}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Alamat:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.address}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Tipe:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.propertyType}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Keterangan:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.description}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Created:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.createdDate} by ${detail.createdBy}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Status:</label>
                    <div class="col-sm-8">
                        <p class="form-control-static">${detail.status}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Upload Gambar Properti:</label>
                    <div class="col-sm-8" style="padding-top: 7px">
                        <g:if test="${detail.attachment!=null && detail.attachment!=""}">
                            <g:link action="downloadFile" id="${detail.attachment}">${detail.attachmentName}</g:link>
                        </g:if>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Code:</label>
                    <div class="col-sm-8">
                        <input type="hidden" name="code" value="${detail.code}" />
                        <p class="form-control-static">${detail.code}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Jumlah Unit:</label>
                    <div class="col-sm-8">
                        <input type="hidden" name="totalUnit" value="${detail.totalUnit}" />
                        <p class="form-control-static">${detail.totalUnit}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Fee:</label>
                    <div class="col-sm-8">
                        <input type="hidden" name="fee" value="${detail.fee}" />
                        <p class="form-control-static">${detail.fee}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Expiry Tanggal:</label>
                    <div class="col-sm-8">
                        <input type="hidden" name="expiryDate" value="${detail.expiryDate}" />
                        <p class="form-control-static">${detail.expiryDate}</p>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <g:if test="${detail.stage == 'Confirm'}">
                    <g:actionSubmit action="approveDeal" class="btn btn-default" value="Kembali" />
                    <button type="submit" onclick="$.blockUI({ message: 'Sedang diproses, harap menunggu.' });" class="btn btn-info pull-right">Simpan</button>
                </g:if>
                <g:else>
                    <g:link action="index" class="btn btn-success pull-right">Selesai</g:link>
                </g:else>
            </div>
        </g:form>
    </div>
</section>
</body>
</html>